# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - index_controller
    - middle_controller
    - ring_controller
    - thumb_controller

  index_controller:
    type: FollowJointTrajectory
    joints:
      - ah_joint10
      - ah_joint11
      - ah_joint12
      - ah_joint13
    action_ns: follow_joint_trajectory
    default: true
  middle_controller:
    type: FollowJointTrajectory
    joints:
      - ah_joint20
      - ah_joint21
      - ah_joint22
      - ah_joint23
    action_ns: follow_joint_trajectory
    default: true
  ring_controller:
    type: FollowJointTrajectory
    joints:
      - ah_joint30
      - ah_joint31
      - ah_joint32
      - ah_joint33
    action_ns: follow_joint_trajectory
    default: true
  thumb_controller:
    type: FollowJointTrajectory
    joints:
      - ah_joint00
      - ah_joint01
      - ah_joint02
      - ah_joint03
    action_ns: follow_joint_trajectory
    default: true